-- ============================================================================
-- Vision CRM — Wave 2: remaining tenant tables
-- ============================================================================
-- Ports the rest of schema.ts into Supabase, applying the SAME tenant-isolation
-- shape proven in Wave 1: company_id NOT NULL + FK -> companies + index, RLS
-- enabled, one FOR ALL policy scoped to current_company_id(). The RLS/index/
-- policy is applied uniformly by the loop at the bottom, so every table is
-- guaranteed the identical treatment — no table can be accidentally left open.
--
-- Two junction tables (chat_channel_members, chat_message_reads) have no
-- company_id of their own and are isolated through their parent instead.
-- ============================================================================

-- ---- Reference / catalog tables (no tenant FKs beyond companies) -----------
create table public.suppliers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null,
  contact_name text, email text, phone text,
  address text, town text, county text, postcode text,
  notes text, active boolean default true,
  created_at timestamptz not null default now()
);

create table public.staff_members (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  first_name text not null, last_name text not null,
  role text, roles text[],
  default_hourly_rate numeric(10, 2),
  email text, phone text, active boolean default true,
  created_at timestamptz not null default now()
);

create table public.quote_types (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  name text not null, sort_order integer default 0, is_active boolean default true
);

create table public.contract_types (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  name text not null, description text, sort_order integer default 0,
  is_active boolean default true, created_at timestamptz not null default now()
);

create table public.lead_results (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  category text not null, label text not null,
  sort_order integer default 0, is_active boolean default true
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null, description text,
  supplier_id uuid references public.suppliers (id), supplier_name text,
  warranty text, active boolean default true,
  created_at timestamptz not null default now()
);

create table public.stock_items (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null, unit_of_measurement text not null,
  price numeric(10, 2),
  supplier_id uuid references public.suppliers (id), supplier_name text,
  description text, barcode_value text, barcode_data text,
  active boolean default true, created_at timestamptz not null default now()
);

create table public.stock_locations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null, description text, active boolean default true,
  created_at timestamptz not null default now()
);

create table public.inventory (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null,
  sku text not null,
  category text not null,
  quantity integer default 0, min_quantity integer default 5,
  unit_price numeric(10, 2), supplier text, description text,
  unique (company_id, sku)   -- SKU unique per tenant, not globally
);

-- ---- Deal lifecycle: contracts / quotes / jobs -----------------------------
create table public.contracts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  contract_number integer,
  lead_id uuid not null references public.leads (id),
  customer_id uuid references public.customers (id),
  contract_date timestamptz,
  office_reference text, office_reference_2 text,
  gross_value numeric(10, 2), salesman text, source text,
  supply_only boolean default false, delivery_method text,
  contract_type text, contract_type_id integer, installation_manager text,
  on_hold boolean default false, hold_reason text,
  hold_date_on timestamptz, hold_date_off timestamptz,
  contract_cancelled boolean default false, cancel_reason text, cancel_date timestamptz,
  sales_area text, sales_director text, balance_reason text, old_balance_reason text,
  invoice_same_as_customer boolean default true,
  invoice_name text, invoice_house_name text, invoice_house_number text,
  invoice_street text, invoice_locality text, invoice_town text,
  invoice_county text, invoice_postcode text,
  fitting_same_as_customer boolean default true,
  fitting_house_name text, fitting_house_number text, fitting_street text,
  fitting_locality text, fitting_town text, fitting_county text,
  fitting_postcode text, fitting_what_3_words text, fitting_directions text,
  send_letters_to_fitting boolean default false,
  estimated_fitting_days numeric(5, 1), installation_completed text,
  signboard_left boolean default false, signboard_date text,
  guarantee_number text, guarantee_date text, insurance_backed_guarantee_ref text,
  notes text, status text default 'active',
  created_at timestamptz not null default now()
);

create table public.quotes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  quote_number text not null,
  lead_id uuid references public.leads (id),
  customer_id uuid references public.customers (id),
  status text default 'draft',
  subtotal numeric(10, 2), tax numeric(10, 2), total numeric(10, 2),
  valid_until timestamptz, notes text, line_items jsonb,
  created_at timestamptz not null default now()
);

create table public.jobs (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  job_number text not null,
  quote_id uuid references public.quotes (id),
  customer_id uuid references public.customers (id),
  status text default 'scheduled',
  scheduled_date timestamptz, completed_date timestamptz,
  assigned_team text[], installation_type text, window_count integer,
  notes text, created_at timestamptz not null default now()
);

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  customer_id uuid references public.customers (id),
  title text not null, type text default 'appointment',
  date timestamptz not null, time text, duration integer default 60,
  location text, assigned_to text, status text default 'scheduled',
  notes text, created_at timestamptz not null default now()
);

-- ---- Attachments / notes / line items --------------------------------------
create table public.documents (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  customer_id uuid references public.customers (id),
  name text not null, file_name text not null, file_type text,
  file_size integer, file_url text not null,
  uploaded_by uuid references public.users (id),
  context text default 'lead', created_at timestamptz not null default now()
);

create table public.lead_notes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  customer_id uuid references public.customers (id),
  content text not null,
  created_by uuid references public.users (id),
  created_at timestamptz not null default now()
);

create table public.contract_notes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  content text not null,
  created_by uuid references public.users (id),
  created_at timestamptz not null default now()
);

create table public.contract_products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  product_name text not null, description text,
  quantity integer default 1, unit_price numeric(10, 2), total_price numeric(10, 2),
  created_at timestamptz not null default now()
);

-- ---- Financials ------------------------------------------------------------
create table public.finance_lines (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  line_type text not null,
  charge_amount numeric(10, 2), payment_amount numeric(10, 2),
  payment_method text, invoice_number text, invoice_details text,
  payment_date timestamptz, notes text,
  created_at timestamptz not null default now()
);

create table public.finance_payments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  finance_line_id uuid references public.finance_lines (id) on delete cascade,
  amount numeric(10, 2) not null,
  payment_method text, payment_date text, reference text,
  created_at timestamptz not null default now()
);

create table public.delivery_lines (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  item_name text not null, comments text, supplier_name text,
  ordered_by_initials text, net_value numeric(10, 2),
  date_ordered text, quantity_ordered integer default 1,
  delivery_due_date text, quantity_received integer default 0, date_received text,
  created_at timestamptz not null default now()
);

create table public.commissions (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  date text, commission_type text,
  staff_member_id uuid references public.staff_members (id), staff_member_name text,
  details text, commission_percent numeric(5, 2), commission_amount numeric(10, 2),
  hours numeric(6, 2), hourly_rate numeric(10, 2), travel_hours numeric(6, 2),
  total_cost numeric(10, 2), comments text, hold_reason text,
  paid boolean default false, date_paid text, paid_by text,
  created_at timestamptz not null default now()
);

create table public.job_invoices (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  date text, invoice_number text,
  supplier_id uuid references public.suppliers (id), supplier_name text,
  description text,
  net_amount numeric(10, 2), vat_amount numeric(10, 2), gross_amount numeric(10, 2),
  document_id uuid, created_at timestamptz not null default now()
);

-- ---- Diary / scheduling ----------------------------------------------------
create table public.fitting_appointments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  work_type text default 'initial_fitting', description text, comments text,
  date text, time text,
  duration_days numeric(5, 1), duration_hours numeric(5, 1), travel_time text,
  confirmed boolean default false, confirmed_method text,
  confirmed_date text, confirmed_by text,
  locked boolean default false, provisional boolean default false,
  completed boolean default false, completed_date text,
  assigned_staff_ids text[], assigned_staff_names text[],
  created_at timestamptz not null default now()
);

-- ---- Activity / messaging --------------------------------------------------
create table public.activities (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  type text not null, description text not null,
  customer_id uuid references public.customers (id),
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  quote_id uuid references public.quotes (id),
  job_id uuid references public.jobs (id),
  user_id uuid references public.users (id),
  created_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  customer_id uuid references public.customers (id),
  content text not null, direction text not null, read boolean default false,
  created_at timestamptz not null default now()
);

-- ---- Settings --------------------------------------------------------------
create table public.company_settings (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  customer_id text, company_name text, address text, telephone text, fax text, email text,
  contact_1_title text, contact_1_name text, contact_2_title text, contact_2_name text,
  business_short_name text, vat_number text, website text,
  logo_1_path text, logo_2_path text, logo_3_path text,
  brand_color_1 text, brand_color_2 text,
  checklist_enabled boolean default false, default_quote_type_id integer,
  tt_enabled boolean default false, tt_user_id text, tt_api_key text, tt_auto_push boolean default false,
  sms_enabled boolean default false, sms_sender_name text, twilio_phone_number text
);

-- ---- Checklists / workflows ------------------------------------------------
create table public.checklist_templates (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  quote_type_id integer not null references public.quote_types (id),
  sort_order integer default 0, action_name text not null,
  assigned_to_id uuid references public.users (id),
  assigned_by_id uuid references public.users (id),
  locked boolean default false,
  due_date_mode text default 'same_day', days_to_add integer default 0,
  days_relative_to text default 'previous_completed',
  notify_on_complete boolean default false, notify_user_ids text[],
  notification_template text, notification_email_subject text, notification_email_body text,
  notify_sms_on_complete boolean default false, sms_template text,
  customer_notify_on_complete boolean default false,
  customer_email_subject text, customer_email_body text,
  customer_notify_sms boolean default false, customer_sms_template text,
  notification_from_address_id uuid, notification_signature text,
  priority text default 'medium'
);

create table public.lead_checklist_items (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  lead_id uuid not null references public.leads (id),
  template_id integer references public.checklist_templates (id),
  sort_order integer default 0, action_name text not null,
  assigned_to_id uuid references public.users (id),
  assigned_by_id uuid references public.users (id),
  locked boolean default false, due_date timestamptz, status text default 'pending',
  completed_by_id uuid, completed_by_name text, completed_at timestamptz,
  notify_on_complete boolean default false, notification_template text,
  comment text, priority text default 'medium',
  created_at timestamptz not null default now()
);

create table public.contract_checklist_templates (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  contract_type_id integer not null references public.contract_types (id),
  sort_order integer default 0, action_name text not null,
  assigned_to_id uuid references public.users (id),
  assigned_by_id uuid references public.users (id),
  locked boolean default false,
  due_date_mode text default 'same_day', days_to_add integer default 0,
  days_relative_to text default 'previous_completed',
  notify_on_complete boolean default false, notify_user_ids text[],
  notification_template text, notification_email_subject text, notification_email_body text,
  notify_sms_on_complete boolean default false, sms_template text,
  customer_notify_on_complete boolean default false,
  customer_email_subject text, customer_email_body text,
  customer_notify_sms boolean default false, customer_sms_template text,
  notification_from_address_id uuid, notification_signature text,
  priority text default 'medium'
);

create table public.contract_checklist_items (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  contract_id uuid not null references public.contracts (id),
  template_id integer references public.contract_checklist_templates (id),
  sort_order integer default 0, action_name text not null,
  assigned_to_id uuid references public.users (id),
  assigned_by_id uuid references public.users (id),
  locked boolean default false, due_date timestamptz, status text default 'pending',
  completed_by_id uuid, completed_by_name text, completed_at timestamptz,
  notify_on_complete boolean default false, notification_template text,
  comment text, priority text default 'medium',
  created_at timestamptz not null default now()
);

create table public.notifications (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  user_id uuid not null references public.users (id),
  type text not null,
  lead_id uuid references public.leads (id),
  contract_id uuid references public.contracts (id),
  checklist_item_id integer,
  title text not null, message text not null, read boolean default false,
  created_at timestamptz not null default now()
);

-- ---- Internal chat ---------------------------------------------------------
create table public.chat_channels (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  name text not null, type text not null,
  created_at timestamptz not null default now()
);

create table public.chat_channel_members (
  id integer generated by default as identity primary key,
  channel_id integer not null references public.chat_channels (id),
  user_id uuid not null references public.users (id),
  joined_at timestamptz not null default now()
);

create table public.chat_messages (
  id integer generated by default as identity primary key,
  channel_id integer not null references public.chat_channels (id),
  company_id uuid not null references public.companies (id),
  sender_id uuid not null references public.users (id),
  content text not null, created_at timestamptz not null default now()
);

create table public.chat_message_reads (
  id integer generated by default as identity primary key,
  message_id integer not null references public.chat_messages (id),
  user_id uuid not null references public.users (id),
  read_at timestamptz not null default now()
);

-- ---- Stock movements -------------------------------------------------------
create table public.stock_transactions (
  id integer generated by default as identity primary key,
  company_id uuid not null references public.companies (id),
  stock_item_id uuid not null references public.stock_items (id),
  stock_location_id uuid not null references public.stock_locations (id),
  contract_id uuid references public.contracts (id),
  type text not null, quantity integer not null, unit_price numeric(10, 2),
  supplier_id uuid references public.suppliers (id), supplier_name text,
  notes text, created_by_id uuid, created_by_name text,
  created_at timestamptz not null default now()
);

-- ---- Email infrastructure --------------------------------------------------
create table public.email_domains (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  domain text not null, sendgrid_domain_id text,
  status text not null default 'pending', dns_records jsonb,
  created_at timestamptz not null default now()
);

create table public.email_sender_addresses (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  domain_id uuid references public.email_domains (id),
  email text not null, name text not null, is_default boolean default false,
  created_at timestamptz not null default now()
);

create table public.user_email_settings (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  user_id uuid not null unique references public.users (id),
  default_from_address_id uuid, email_signature text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.email_templates (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  name text not null, subject text default '', category text default 'custom',
  blocks jsonb not null default '[]', global_styles jsonb not null default '{}',
  is_industry_template boolean default false, thumbnail_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.email_campaigns (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id),
  template_id uuid references public.email_templates (id),
  name text not null, subject text not null,
  from_address_id uuid references public.email_sender_addresses (id),
  status text not null default 'draft',
  recipient_count integer default 0, sent_count integer default 0,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- Apply the identical tenant-isolation treatment to every company_id table.
-- Looping guarantees no table is left with RLS off or a mismatched policy.
-- ============================================================================
do $$
declare
  t text;
  tenant_tables text[] := array[
    'suppliers','staff_members','quote_types','contract_types','lead_results',
    'products','stock_items','stock_locations','inventory','contracts','quotes',
    'jobs','appointments','documents','lead_notes','contract_notes',
    'contract_products','finance_lines','finance_payments','delivery_lines',
    'commissions','job_invoices','fitting_appointments','activities','messages',
    'company_settings','checklist_templates','lead_checklist_items',
    'contract_checklist_templates','contract_checklist_items','notifications',
    'chat_channels','chat_messages','stock_transactions','email_domains',
    'email_sender_addresses','user_email_settings','email_templates','email_campaigns'
  ];
begin
  foreach t in array tenant_tables loop
    execute format('create index if not exists %I on public.%I (company_id)',
                   t || '_company_id_idx', t);
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy "tenant isolation" on public.%I for all to authenticated '
      'using (company_id = public.current_company_id()) '
      'with check (company_id = public.current_company_id())', t);
  end loop;
end $$;

-- ---- Junction tables: no company_id; isolate via the parent ----------------
alter table public.chat_channel_members enable row level security;
create policy "tenant isolation via channel"
  on public.chat_channel_members for all to authenticated
  using ( exists (
    select 1 from public.chat_channels c
    where c.id = channel_id and c.company_id = public.current_company_id() ) )
  with check ( exists (
    select 1 from public.chat_channels c
    where c.id = channel_id and c.company_id = public.current_company_id() ) );

alter table public.chat_message_reads enable row level security;
create policy "tenant isolation via message"
  on public.chat_message_reads for all to authenticated
  using ( exists (
    select 1 from public.chat_messages m
    where m.id = message_id and m.company_id = public.current_company_id() ) )
  with check ( exists (
    select 1 from public.chat_messages m
    where m.id = message_id and m.company_id = public.current_company_id() ) );
