-- ============================================================================
-- Directional customer relationships
-- ============================================================================
-- A relationship reads differently from each side: "David referred Margaret"
-- shows as "Referred by David" on Margaret's record and "Referred Margaret" on
-- David's. So each TYPE is a pair of labels (forward / inverse), and each LINK
-- stores the wording for each side (label_a = customer_id's side,
-- label_b = related_customer_id's side). Symmetric types (Family, Neighbour)
-- have forward = inverse.
-- ============================================================================

create table if not exists public.relationship_types (
  id            integer generated by default as identity primary key,
  company_id    uuid not null references public.companies (id),
  forward_label text not null,    -- how it reads from the "subject" side (e.g. "Referred")
  inverse_label text not null,    -- how it reads from the "object" side  (e.g. "Referred by")
  sort_order    integer default 0,
  is_active     boolean default true,
  created_at    timestamptz not null default now(),
  unique (company_id, forward_label, inverse_label)
);
create index if not exists relationship_types_company_idx on public.relationship_types (company_id);
alter table public.relationship_types enable row level security;
create policy "relationship_types: tenant isolation"
  on public.relationship_types for all to authenticated
  using ( company_id = public.current_company_id() )
  with check ( company_id = public.current_company_id() );

-- Per-link wording for each side.
alter table public.customer_relationships
  add column if not exists label_a text,   -- shown on customer_id's record
  add column if not exists label_b text;   -- shown on related_customer_id's record

-- Backfill any existing rows symmetrically from the old freeform text.
update public.customer_relationships
set label_a = coalesce(label_a, relationship_type),
    label_b = coalesce(label_b, relationship_type)
where relationship_type is not null and (label_a is null or label_b is null);

-- Seed a starter set of relationship-type pairs for every existing tenant.
insert into public.relationship_types (company_id, forward_label, inverse_label, sort_order)
select c.id, p.fwd, p.inv, p.ord
from public.companies c
cross join (values
  ('Family', 'Family', 1),
  ('Spouse / partner', 'Spouse / partner', 2),
  ('Parent of', 'Child of', 3),
  ('Neighbour', 'Neighbour', 4),
  ('Referred', 'Referred by', 5),
  ('Landlord of', 'Tenant of', 6),
  ('Colleague', 'Colleague', 7),
  ('Previous owner', 'Previous owner', 8),
  ('Other', 'Other', 9)
) as p(fwd, inv, ord)
on conflict (company_id, forward_label, inverse_label) do nothing;
